### ISSUE TITLE
Make the backend faster

### ISSUE THREAD

**Issue by dibyadas** [kossiitkgp/profile-generator#6]
~~None of the process in the backend is asynchronous~~.The profile generating part of the template is not asynchronous. Due you which the process becomes slow. ~~For ex:- In the mailing part of the app, it should send a 200 OK status as soon as the POST request is received. The sending part can be done afterwards~~. Similarly, in the template part, it should be divided into modules and made asynchronous for faster execution.

**Comment by aribis369** [comment]
@dibyadas One I want to bring to your notice that our programs in both cases cannot be made asynchronous in modular sense. 
* for the mailing part we have to first we get the message and the users email id, then we sent a mail to KOSS's gmail account about this and then the program ends. We cannot divide the 2 processes of getting user data and sending mail and it async. as async. processes are parallel processes and execute in random order, our program must go in a particular procedure(i.e. first get users data and then send mail)
* for template part we cannot do aysnc. because of the same reason, we cannot make processes aysnch. which depend upon other processes to complete. async. is used for almost independent functions to execute in parallel.
BUT one thing can be done that client requests can be made async by using 'Celery'. I can do that part if assigned.

**Comment by dibyadas** [comment]
@aribis369 I think you have misunderstood this part a bit. 

* For the mail part I said, as soon as we receive the POST request, we can make the returning of the response and the sending of mail asynchronous. The mail can be sent after the response has been sent back. There is no problem with this. No point in sending the response back *only* after the mail has been sent. 

* For the template part,  as I said, we can modularize it, and send the data as soon as the processes are completed, no matter their order. The data in the profile page will be updated accordingly. The process we are talking about are independent of each other and fill up different `<div>` tags. Hence, they can be made asynchronous.

**Comment by aribis369** [comment]
@dibyadas Using Celery is also a headache as it requires a rabbitmq server as broker. Do you have any other things to specify or suggest on this topic.

**Comment by aribis369** [comment]
@dibyadas on the comment you gave I want to reply that in the mailing part you and I are on the same frequency, I agree with you and for accomplishing it Celery could be used. But our call from contact page is made to your heroku app and for using Celery we have to use rabbitmq server. 
For the template part I disagree with you we have just 1 call to the gh api and then assignments of values to content dictionary. API call is a must before assignment and I think we don't need async. processes for just different assignment. You can argue that we can atleast send the the hardcoded previously know data and data from gh api from 2 different process but is it worth of so much work done to be done.

**Comment by dibyadas** [comment]
The mail sending part is now asynchronous. :)

**Comment by dibyadas** [comment]
The user information extraction will use GraphQL.. Ref issue #8
